databases:
  - name: daily-tracker-db
    databaseName: daily_tracker
    user: daily_tracker_user

services:
  - type: web
    name: daily-tracker-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: daily-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PASSWORD_SALT
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0